### ISSUE TITLE
Is it the same engine what use https://play-cs.com/?? 

### ISSUE THREAD

**Issue by deimjons** [VadimDez/Counter-Strike-JS#222]
Is it the same engine what use https://play-cs.com/??

**Comment by GYKgamer** [comment]
no

**Comment by AlinGheaja** [comment]
> Is it the same engine what use https://play-cs.com/??

did you find out what engine is on play-cs ?

**Comment by GYKgamer** [comment]
> > Is it the same engine what use https://play-cs.com/??
> 
> did you find out what engine is on play-cs ?

https://github.com/FWGS/xash3d
